DROP TABLE IF EXISTS films, genres_of_film, users, likes, friendship, genres, mpa;

CREATE TABLE IF NOT EXISTS genres
(
    genre_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_name varchar(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS mpa
(
    mpa_id   int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mpa_name varchar(10) NOT NULL UNIQUE,
    description text        NOT NULL
);

CREATE TABLE IF NOT EXISTS films
(
    film_id      int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_name    varchar NOT NULL,
    mpa_id    integer NOT NULL REFERENCES mpa,
    description  text    NOT NULL,
    release_date date    NOT NULL,
    duration     integer NOT NULL
);

CREATE TABLE IF NOT EXISTS genres_of_film
(
    genre_id int NOT NULL REFERENCES genres,
    film_id  int NOT NULL REFERENCES films
);

CREATE TABLE IF NOT EXISTS users
(
    user_id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar NOT NULL,
    login     varchar NOT NULL,
    email     varchar NOT NULL,
    birthday  date    NOT NULL
);

CREATE TABLE IF NOT EXISTS likes
(
    user_id int NOT NULL REFERENCES users,
    film_id int NOT NULL REFERENCES films
);

CREATE TABLE IF NOT EXISTS friendship
(
    user_id            int NOT NULL REFERENCES users,
    friend_id          int NOT NULL REFERENCES users,
    status bool default false
);